# fly.toml file generated for world on 2023-04-10T13:07:21+08:00

app = "world"
kill_signal = "SIGINT"
kill_timeout = 5
primary_region = "sin"

[[services]]
  protocol = "tcp"
  internal_port = 80
  processes = ["app"]

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
  [services.concurrency]
    type = "connections"
    hard_limit = 1000
    soft_limit = 1000
